#!/bin/bash

chmod +x "$CONFIG_DIR/plugins/aerospacer.sh"
chmod +x "$CONFIG_DIR/plugins/i3_status.sh"

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar height=28        \
                 position=bottom  \
                 color=0xff000000 \
                 sticky=on        \
                 topmost=on       \
                 padding_left=0   \
                 padding_right=0  \
                 margin=0         \
                 y_offset=0       \
                 corner_radius=0

sketchybar --add event aerospace_workspace_change

##### Defaults #####
sketchybar --default icon.font="FiraCode Nerd Font:Bold:14.0" \
                     label.font="FiraCode Nerd Font:Bold:14.0" \
                     icon.color=$WHITE \
                     label.color=$WHITE \
                     background.padding_left=0 \
                     background.padding_right=0 \
                     label.padding_left=12 \
                     label.padding_right=12 \
                     icon.padding_left=0 \
                     icon.padding_right=0

##### Workspaces (Left) #####
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item ws.$sid left \
             --subscribe ws.$sid aerospace_workspace_change \
             --set ws.$sid \
                   icon="$sid" \
                   icon.padding_left=10 \
                   icon.padding_right=10 \
                   label.drawing=off \
                   click_script="aerospace workspace $sid" \
                   script="$PLUGIN_DIR/aerospacer.sh $sid" \
                   background.corner_radius=0 \
                   background.height=28
done

##### System Info (Right) #####
sketchybar --add item i3_status right \
           --subscribe i3_status aerospace_workspace_change \
           --set i3_status update_freq=5 \
                           script="$PLUGIN_DIR/i3_status.sh" \
                           label.padding_right=15
