#!/bin/bash

chmod +x "$CONFIG_DIR/plugins/icon_map_fn.sh"

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=32        \
                 blur_radius=20   \
                 position=top     \
                 sticky=on        \
                 padding_left=10  \
                 padding_right=10 \
                 margin=10        \
                 y_offset=10      \
                 color=$BAR_COLOR \
                 corner_radius=10 \
                 list_window=on

sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="FiraCode Nerd Font:Semibold:14.0"
  label.font="FiraCode Nerd Font:Semibold:14.0"
  icon.color=$ICON_COLOR
  label.color=$TEXT_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4

  background.color=$ITEM_BG_COLOR
  background.corner_radius=4
  background.height=20
  background.drawing=off
)
sketchybar --default "${default[@]}"

##### Left side items #####
source $ITEM_DIR/apple.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh

##### Center items #####
source $ITEM_DIR/spaces.sh

##### Right side items #####
source $ITEM_DIR/calendar.sh

##### Force all scripts to run the first time #####
sketchybar --update
sketchybar --trigger aerospace_workspace_change
